# ============================= #
#                               #
#  espanso configuration file   #
#                               #
# ============================= #

# This is the default configuration file, change it as you like it
# You can refer to the official documentation:
# https://espanso.org/docs/

# Matches are the substitution rules, when you type the "trigger" string
# it gets replaced by the "replace" string.

# =============================================================================

global_vars:
  - name: days_lived
    type: script
    params:
      args:
        - python
        - "%CONFIG%\\scripts\\dates.pyw"
        - calc_days_lived
  - name: ordinal_day
    type: script
    params:
      args:
        - python
        - "%CONFIG%\\scripts\\dates.pyw"
        - ordinal_day
  - name: "mtime"
    type: "date"
    params:
      format: "%H%M"
  - name: "otime"
    type: "date"
    params:
      format: "%H:%M"
  - name: "iso_today"
    type: "date"
    params:
      format: "%Y-%m-%d"
  - name: "reg_today"
    type: "date"
    params:
      format: "%b %d, %Y"
